resources:
  containers:
  - container: yarn
    image: yarnpkg/dev:latest
jobs:
- job: Linux
  pool: default
  workspace:
    clean: all
  #container: yarn
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: 'Install Node.js'

  - bash: |
      yarn
      yarn run build
      ls -lhR bin
      ls -lhR lib
    displayName: 'Install and build'

  - script: |
      cd packages/pkg-tests
      yarn
    displayName: 'Install the acceptance tests'

  - script: |
      cd packages/pkg-tests
      yarn jest yarn.test.js
    displayName: 'Run the acceptance tests'
    condition: always()
    
  - script: |
      cd packages/pkg-tests
      yarn jest yarn.test.js
    displayName: 'Run the acceptance tests'
    condition: always()
    
  - script: |
      cd packages/pkg-tests
      yarn jest yarn.test.js
    displayName: 'Run the acceptance tests'
    condition: always()
    
  - script: |
      date -u "+%Y.%m.%d-%H.%M.%S.%N"
      for i in {1..1000};
      do    
        yarn --version; 
      done
      date -u "+%Y.%m.%d-%H.%M.%S.%N"
      #sudo apt install -y httping traceroute
      #httping github-production-release-asset-2e65be.s3.amazonaws.com -c 10
      #httping google.com -c 10
      #httping mseng.visualstudio.com -c 10
      #httping tingms.visualstudio.com -c 10
      
      #traceroute -m 254 52.216.161.123
      #traceroute -m 100 mseng.visualstudio.com
      #traceroute -m 100 github-production-release-asset-2e65be.s3.amazonaws.com
      
      #wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test1000.zip
      #wget -O /dev/null https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz
      
      #mkdir test_temp
      #cd test_temp
      #echo "{\"name\":\"test\",\"license\":\"MIT\"}" > package.json
      #yarn add https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz --cache-folder ./cache
