version: 2

docker_defaults: &docker_defaults
  docker:
    - image: yarnpkg/dev:latest
  working_directory: ~/project/yarn

run_steps: &run_steps
  steps:
    - run:
        name: ad-hoc
        command: |
          git version; git config --list
          printenv|sort
          cat /etc/os-release
          yarn cache clean
          
          apt update
          apt install -y curl
          
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

          apt update
          apt install -y httping traceroute yarn
          #httping github-production-release-asset-2e65be.s3.amazonaws.com -c 10
          #httping google.com -c 10
          #httping mseng.visualstudio.com -c 10
          #httping tingms.visualstudio.com -c 10
          
          #traceroute -m 100 mseng.visualstudio.com
          #traceroute -m 100 52.216.161.123
          #traceroute -m 100 github-production-release-asset-2e65be.s3.amazonaws.com
      
          #wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test1000.zip
          git clone https://github.com/TingluoHuang/yarn
          cd yarn
          git checkout users/tihuang/pipelines
          yarn install --frozen-lockfile
          yarn build
          cd packages/pkg-tests
          yarn
          #yarn jest yarn.test.js
          #yarn jest yarn.test.js
          #yarn jest yarn.test.js
          
          date -u "+%Y.%m.%d-%H.%M.%S.%N"
          for i in {1..1000};
          do    
            yarn --version; 
          done
          date -u "+%Y.%m.%d-%H.%M.%S.%N"
          #yarn --cwd packages/pkg-tests test-only -u --maxWorkers 3
          
          #wget -O /dev/null https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz
          
          #mkdir test_temp
          #cd test_temp
          #echo "{\"name\":\"test\",\"license\":\"MIT\"}" > package.json
          #yarn add https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz --cache-folder ./cache

default_filters: &default_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-linux-node10:
    <<: *docker_defaults
    <<: *run_steps

workflows:
  version: 2

  install-test-build-and-publish:
    jobs:
      - test-linux-node10:
          filters: *default_filters
