version: 2

docker_defaults: &docker_defaults
  docker:
    - image: yarnpkg/dev:latest
  working_directory: ~/project/yarn

attach_workspace: &attach_workspace
  attach_workspace:
      at: ~/project

run_steps: &run_steps
  steps:
    - checkout
    - run:
        name: ad-hoc
        command: |
          git version; git config --list
          printenv|sort
          cat /etc/os-release
          yarn cache clean
    - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
    - run:
        name: Build Yarn for testing
        command: |
          if [ "$CIRCLE_BRANCH" == 'master' ]; then
            ./scripts/set-dev-version.js
          fi;
          yarn build
    - run:
        name: Tests
        command: |
          # Limit maxWorkers to 3 to avoid OOM on CircleCI
          yarn test-only --maxWorkers 3

default_filters: &default_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-linux-node10:
    <<: *docker_defaults
    <<: *run_steps

workflows:
  version: 2

  install-test-build-and-publish:
    jobs:
      - test-linux-node10:
          filters: *default_filters
