version: 2

docker_defaults: &docker_defaults
  docker:
    - image: yarnpkg/dev:latest
  working_directory: ~/project/yarn

attach_workspace: &attach_workspace
  attach_workspace:
      at: ~/project

run_steps: &run_steps
  steps:
    - run:
        name: ad-hoc
        command: |
          git version; git config --list
          printenv|sort
          cat /etc/os-release
          yarn cache clean
          wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test1000.zip
          git clone https://github.com/TingluoHuang/yarn
          cd yarn
          git checkout users/tihuang/pipelines
          yarn install --frozen-lockfile
          yarn build
          yarn test-only --maxWorkers 3

default_filters: &default_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-linux-node10:
    <<: *run_steps

workflows:
  version: 2

  install-test-build-and-publish:
    jobs:
      - test-linux-node10:
          filters: *default_filters
